# Generated by Django 4.2 on 2025-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовок About')),
                ('description2', models.TextField(verbose_name='Описание About')),
                ('image2', models.ImageField(upload_to='settings', verbose_name='Фото About')),
            ],
            options={
                'verbose_name_plural': 'Главная НАстройки',
            },
        ),
    ]
