# Generated by Django 4.2 on 2025-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_imageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Наши Бонусы')),
            ],
            options={
                'verbose_name_plural': 'Наши бонусы',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='title_bonus1',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок Bonus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title_bonus2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок Bonus2'),
            preserve_default=False,
        ),
    ]
