# Generated by Django 4.2 on 2025-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_bonus_settings_title_bonus1_settings_title_bonus2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('role', models.TextField(verbose_name='Должность')),
                ('image', models.ImageField(upload_to='team', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Наша команда',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='title_team',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовок Team'),
            preserve_default=False,
        ),
    ]
