# Generated by Django 4.2 on 2025-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_team_settings_title_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
