# Generated by Django 4.2 on 2025-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Экопродукты', max_length=155, null=True, verbose_name='Заголовок')),
                ('title2', models.CharField(blank=True, default='Продукты с заботой о планете', max_length=155, null=True, verbose_name='Заголовок 2')),
                ('title_obj', models.CharField(max_length=155, verbose_name='Заголовка Объекта')),
                ('image_obj', models.ImageField(upload_to='services', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Наши услуги',
            },
        ),
    ]
