# Generated by Django 4.2 on 2025-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='title_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Наши Бонусы'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Наши Бонусы'),
        ),
        migrations.AddField(
            model_name='services',
            name='title2_ky',
            field=models.CharField(blank=True, default='Продукты с заботой о планете', max_length=155, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='services',
            name='title2_ru',
            field=models.CharField(blank=True, default='Продукты с заботой о планете', max_length=155, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ky',
            field=models.CharField(blank=True, default='Экопродукты', max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_obj_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_obj_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(blank=True, default='Экопродукты', max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description2_ky',
            field=models.TextField(null=True, verbose_name='Описание About'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description2_ru',
            field=models.TextField(null=True, verbose_name='Описание About'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title2_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок About'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title2_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок About'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_bonus1_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Bonus'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_bonus1_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Bonus'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_bonus2_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Bonus2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_bonus2_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Bonus2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_team_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Team'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_team_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_ky',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='team',
            name='role_ru',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
    ]
